# Generated by Django 4.0.1 on 2022-03-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('London', 'New'), ('Sheffield', 'Accepted'), ('Liverpool', 'Completed'), ('Bristol', 'Sussex'), ('Hertfordshire', 'Hertfordshire'), ('Birmingham', 'Glasgow'), ('Wales', 'Wales'), ('Kent', 'Kent'), ('Leicester', 'Leicester'), ('Coventry', 'Coventry')], max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, unique=True)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.location')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.location')),
            ],
        ),
    ]
