# Generated by Django 4.0.1 on 2022-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('Sheffield', 'Accepted'), ('Liverpool', 'Completed'), ('Bristol', 'Sussex'), ('Hertfordshire', 'Hertfordshire'), ('Birmingham', 'Glasgow'), ('Wales', 'Wales'), ('Kent', 'Kent'), ('Leicester', 'Leicester'), ('Coventry', 'Coventry')], max_length=20),
        ),
    ]
