# Generated by Django 4.0.1 on 2022-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deliveryman',
            field=models.BooleanField(default=False),
        ),
    ]
