# Generated by Django 4.0.1 on 2022-03-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_deliveryman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_deliveryman',
            new_name='is_delivery_person',
        ),
    ]
