# Generated by Django 4.0.1 on 2022-03-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crate',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
