# Generated by Django 4.0.1 on 2022-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_crate_status_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='status',
            field=models.CharField(choices=[('Shelf', 'shelf'), ('Pick-up room', 'pick_up_room'), ('in transit', 'in_transit'), ('delivered', 'delivered')], default='Shelf', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Shelf', 'shelf'), ('Pick-up room', 'pick_up_room'), ('in transit', 'in_transit'), ('delivered', 'delivered')], default='Shelf', max_length=30),
        ),
    ]
