# Generated by Django 4.0.1 on 2022-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_crate_status_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='status',
            field=models.CharField(choices=[('shelf', 'shelf'), ('pick up room', 'pick up room'), ('in transit', 'in transit'), ('delivered', 'delivered')], default='Shelf', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('shelf', 'shelf'), ('pick up room', 'pick up room'), ('in transit', 'in transit'), ('delivered', 'delivered')], default='Shelf', max_length=30),
        ),
    ]
