# Generated by Django 4.0.1 on 2022-03-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_crate_status_alter_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='storage_price',
            new_name='return_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='storage_price',
            new_name='return_price',
        ),
    ]
