# Generated by Django 4.0.1 on 2022-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_storage_price_crate_return_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='status',
            field=models.CharField(choices=[('Shelf', 'Shelf'), ('Pick up room', 'Pick up room'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Return initiated', 'Return initiated')], default='Shelf', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Shelf', 'Shelf'), ('Pick up room', 'Pick up room'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Return initiated', 'Return initiated')], default='Shelf', max_length=30),
        ),
    ]
