# Generated by Django 4.0.1 on 2022-03-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_crate_status_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='crate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.crate'),
        ),
    ]
