# Generated by Django 4.0.1 on 2022-03-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_item_crate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='status',
            field=models.CharField(choices=[('Shelf', 'Shelf'), ('Ordered', 'Ordered'), ('Pick up room', 'Pick up room'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Return initiated', 'Return initiated')], default='Shelf', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Shelf', 'Shelf'), ('Ordered', 'Ordered'), ('Pick up room', 'Pick up room'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Return initiated', 'Return initiated')], default='Shelf', max_length=30),
        ),
    ]
