# Generated by Django 4.0.1 on 2022-03-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_crate_status_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='change_crate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_item_location', to='inventory.crate'),
        ),
        migrations.AlterField(
            model_name='item',
            name='crate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_storage', to='inventory.crate'),
        ),
    ]
