# Generated by Django 4.0.1 on 2022-03-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_return_price_return_return_total_return_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='note',
        ),
    ]
