# Generated by Django 4.0.1 on 2022-03-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_return_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='item_storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
