# Generated by Django 4.0.1 on 2022-03-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_company_return_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='item_storage',
        ),
    ]
